server:
  port: 8081
  servlet:
    context-path: /admin
  tomcat:
    uri-encoding: utf-8

spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true
    view:
      suffix: .html
    static-path-pattern: /**

  freemarker:
    suffix: .html
    cache: false
    request-context-attribute: request
    settings:
      classic_compatible: true

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/

