# 服务端口
server:
  port: 9000

# 服务名称
spring:
  application:
    name: rain-gateway

  # 网关配置    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
      - id: rain-manager
        uri: lb://rain-manager
        predicates:
        - Path=/manager/**
        
      - id: rain-resource
        uri: lb://rain-resource
        predicates:
          - Path=/resource/**

      - id: rain-user
        uri: lb://rain-user
        predicates:
          - Path=/user/**
          
      - id: rain-auth
        uri: lb://rain-auth
        predicates:
          - Path=/auth/**

management:
  endpoint:
    conditions:
      enabled: true
